name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi, thank you for creating for your first issue! Please be nice =)'
        pr-message: 'Hello! This seems to be your first pull request! Thanks =)'
