name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "Hey! Looks like this issue hasn't had much activity, so we've marked it as stale."
        stale-pr-message: "Hey! Looks like this pull request hasn't had much activity, so we've marked it as stale."
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
